# Using Python for Research Homework: Week 4, Case Study 3

Homophily is a property of networks.  Homophily occurs when nodes that are neighbors in a network also share a characteristic more often than nodes that are not network neighbors.  In this case study, we will investigate homophily of several characteristics of individuals connected in social networks in rural India.

### Exercise 1
In Exercise 1, we will calculate the chance homophily for an arbitrary characteristic. Homophily is the proportion of edges in the network whose constituent nodes share that characteristic.

How much homophily do we expect by chance? If characteristics are distributed completely randomly, the probability that two nodes \(x\) and \(y\) share characteristic \(a\) is the probability both nodes have characteristic \(a\) , which is the marginal probability of \(a\) squared. The total probability that nodes \(x\) and \(y\) share their characteristic is therefore the sum of the square of the marginal probabilities of each characteristic in the network.

<strong>Instructions</strong>
<ul><li>Create a function <code>marginal_prob</code> that takes a dictionary <code>chars</code> with personal IDs as keys and characteristics as values; it should return a dictionary with characteristics as keys and their marginal probability (frequency of occurence of a characteristic divided by the sum of frequencies of each characteristic) as values.</li>
<li>Create a function <code>chance_homophily(chars)</code> that takes a dictionary <code>chars</code> defined as above and computes the chance homophily (homophily due to chance alone) for that characteristic.</li>
<li>A sample of three peoples' favorite colors is given in <code>favorite_colors</code>. Use your function to compute the chance homophily in this group, and store it as <code>color_homophily</code>.</li>
<li>Print <code>color_homophily</code>.</li></ul>

In [57]:
from collections import Counter
import numpy as np

def marginal_prob(chars):
    # Enter code here!
    freq = {}
    for c in chars.values():
        if c in freq:
            freq[c] += 1
        else:
            freq[c] = 1
    
    n = sum(freq.values())
    
    for k, v in freq.items():
        freq[k] = v / n

    
    return freq
        
def chance_homophily(chars):
    # Enter code here!
    chance_homophily = 0
    marginal = marginal_prob(chars=chars)
    for color_count in marginal.values():
        chance_homophily += (color_count/sum(marginal.values()))**2
    return chance_homophily

favorite_colors = {
    "ankit":  "red",
    "xiaoyu": "blue",
    "mary":   "blue"
}

color_homophily = chance_homophily(favorite_colors)
print(color_homophily)
# marginal_prob(favorite_colors)

0.5555555555555556

### Exercise 2

In the remaining exercises, we will calculate actual homophily in these village and compare the obtained values to those obtained by chance. In this exercise, we subset the data into individual villages and store them.

#### Instructions 

- `individual_characteristics.dta` contains several characteristics for each individual in the dataset such as age, religion, and caste. Use the `pandas` library to read in and store these characteristics as a dataframe called `df`.
- Store separate datasets for individuals belonging to Villages 1 and 2 as `df1` and `df2`, respectively.
- Note that some attributes may be missing for some individuals. In this case study, we will ignore rows of data where some column information is missing.
- Use the head method to display the first few entries of `df1`.

In [119]:
import pandas as pd

df  = pd.read_csv("https://courses.edx.org/asset-v1:HarvardX+PH526x+2T2019+type@asset+block@individual_characteristics.csv", low_memory=False, index_col=0,)
df1 = df[df.village == 1]
df2 = df[df.village == 2]

# Enter code here!
df1.head(10)

,village,adjmatrix_key,pid,hhid,resp_id,resp_gend,resp_status,age,religion,caste,...,privategovt,work_outside,work_outside_freq,shgparticipate,shg_no,savings,savings_no,electioncard,rationcard,rationcard_colour
0,1,5,100201,1002,1,1,Head of Household,38,HINDUISM,OBC,...,PRIVATE BUSINESS,Yes,0.0,No,NaN,No,NaN,Yes,Yes,GREEN
1,1,6,100202,1002,2,2,Spouse of Head of Household,27,HINDUISM,OBC,...,NaN,NaN,NaN,No,NaN,No,NaN,Yes,Yes,GREEN
2,1,23,100601,1006,1,1,Head of Household,29,HINDUISM,OBC,...,OTHER LAND,No,NaN,No,NaN,No,NaN,Yes,Yes,GREEN
3,1,24,100602,1006,2,2,Spouse of Head of Household,24,HINDUISM,OBC,...,PRIVATE BUSINESS,No,NaN,Yes,1.0,Yes,1.0,Yes,No,NaN
4,1,27,100701,1007,1,1,Head of Household,58,HINDUISM,OBC,...,OTHER LAND,No,NaN,No,NaN,No,NaN,Yes,Yes,GREEN
5,1,28,100702,1007,2,2,Spouse of Head of Household,40,HINDUISM,OBC,...,OWN LAND,No,NaN,No,NaN,No,NaN,Yes,Yes,GREEN
6,1,33,100801,1008,1,1,Head of Household,54,HINDUISM,OBC,...,OWN,No,NaN,No,NaN,No,NaN,Yes,Yes,GREEN
7,1,34,100802,1008,2,2,Spouse of Head of Household,45,HINDUISM,OBC,...,LAND LORD,No,NaN,No,NaN,No,NaN,Yes,Yes,GREEN
8,1,37,100805,1008,5,2,Other,45,HINDUISM,OBC,...,NaN,NaN,NaN,No,NaN,No,NaN,Yes,Yes,RED
9,1,38,100806,1008,6,1,Other,40,HINDUISM,OBC,...,GOVERNMENT,No,NaN,No,NaN,No,NaN,Yes,Yes,RED

In [60]:
df2

,village,adjmatrix_key,pid,hhid,resp_id,resp_gend,resp_status,age,religion,caste,...,privategovt,work_outside,work_outside_freq,shgparticipate,shg_no,savings,savings_no,electioncard,rationcard,rationcard_colour
203,2,1,200101,2001,1,1,Head of Household,33,HINDUISM,GENERAL,...,OTHERS,Yes,0.0,No,NaN,No,NaN,Yes,Yes,YELLOW
204,2,6,200201,2002,1,1,Head of Household,35,HINDUISM,GENERAL,...,OTHERS,No,NaN,No,NaN,No,NaN,Yes,Yes,YELLOW
205,2,7,200202,2002,2,2,Spouse of Head of Household,30,HINDUISM,GENERAL,...,OTHERS,No,NaN,Yes,1.0,Yes,1.0,Yes,Yes,YELLOW
206,2,12,200401,2004,1,1,Head of Household,42,HINDUISM,GENERAL,...,OTHERS,No,NaN,No,NaN,Yes,1.0,Yes,Yes,YELLOW
207,2,13,200402,2004,2,2,Spouse of Head of Household,39,HINDUISM,GENERAL,...,NaN,NaN,NaN,Yes,1.0,No,NaN,Yes,Yes,YELLOW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401,2,753,216902,2169,2,2,Spouse of Head of Household,48,HINDUISM,GENERAL,...,NaN,NaN,NaN,No,NaN,No,NaN,Yes,Missing,YELLOW
402,2,754,216903,2169,3,1,Other,32,HINDUISM,GENERAL,...,OTHERS,Yes,0.0,No,NaN,No,NaN,Yes,Yes,YELLOW
403,2,755,216904,2169,4,2,Other,24,HINDUISM,OBC,...,NaN,NaN,NaN,No,NaN,No,NaN,Yes,Missing,GREEN
404,2,756,216905,2169,5,2,Other,22,HINDUISM,GENERAL,...,OTHERS,Yes,0.0,No,NaN,No,NaN,Yes,Yes,YELLOW
405,2,757,216906,2169,6,1,Other,26,HINDUISM,GENERAL,...,OTHERS,Yes,0.0,No,NaN,No,NaN,Yes,Yes,YELLOW

### Exercise 3 

In this exercise, we define a few dictionaries that enable us to look up the sex, caste, and religion of members of each village by personal ID. For Villages 1 and 2, their personal IDs are stored as `pid`.

#### Instructions 
- Define dictionaries with personal IDs as keys and a given covariate for that individual as values. Complete this for the sex, caste, and religion covariates, for Villages 1 and 2.
- For Village 1, store these dictionaries into variables named `sex1`, `caste1`, and `religion1`.
- For Village 2, store these dictionaries into variables named `sex2`, `caste2`, and `religion2`.

In [120]:
sex1 = df1.set_index("pid")["resp_gend"].to_dict()
caste1 = df1.set_index("pid")["caste"].to_dict()
religion1 = df1.set_index("pid")["religion"].to_dict()

sex2 = df2.set_index("pid")["resp_gend"].to_dict()
caste2 = df2.set_index("pid")["caste"].to_dict()
religion2 = df2.set_index("pid")["religion"].to_dict()

### Exercise 4

In this exercise, we will print the chance homophily of several characteristics of Villages 1 and 2. 

#### Instructions 
-  Use `chance_homophily` to compute the chance homophily for sex, caste, and religion In Villages 1 and 2. Is the chance homophily for any attribute very high for either village?

In [126]:
# Enter your code here.
ref = {'sex1': sex1, 'sex2': sex2, 'caste1':caste1, 'caste2':caste2, 'religion1': religion1, 'religion2': religion2, }
for k, v in ref.items():
    print('{} : {}'.format(k, chance_homophily(v)))

sex1 : 0.5027299861680701
sex2 : 0.5005945303210464
caste1 : 0.6741488509791551
caste2 : 0.425368244800893
religion1 : 0.9804896988521925
religion2 : 1.0

### Exercise 5

In this exercise, we will create a function that computes the observed homophily given a village and characteristic.

#### Instructions 
- Complete the function `homophily()`, which takes a network `G`, a dictionary of node characteristics `chars`, and node IDs `IDs`. For each node pair, determine whether a tie exists between them, as well as whether they share a characteristic. The total count of these is `num_ties` and `num_same_ties`, respectively, and their ratio is the homophily of chars in `G`. Complete the function by choosing where to increment `num_same_ties` and `num_ties`.

In [129]:
def homophily(G, chars, IDs):
    """
    Given a network G, a dict of characteristics chars for node IDs,
    and dict of node IDs for each node in the network,
    find the homophily of the network.
    """
    num_same_ties = 0
    num_ties = 0
    for n1, n2 in G.edges():
        if IDs[n1] in chars and IDs[n2] in chars:
            if G.has_edge(n1, n2):
                # Should `num_ties` be incremented?  What about `num_same_ties`?
                num_ties += 1
                if chars[IDs[n1]] == chars[IDs[n2]]:
                    # Should `num_ties` be incremented?  What about `num_same_ties`?
                    num_same_ties += 1
    return (num_same_ties / num_ties)

### Exercise 6

In this exercise, we will obtain the personal IDs for Villages 1 and 2. These will be used in the next exercise to calculate homophily for these villages.

#### Instructions 
- In this dataset, each individual has a personal ID, or PID, stored in `key_vilno_1.csv` and `key_vilno_2.csv` for villages 1 and 2, respectively. `data_filepath1` and `data_filepath2` contain the URLs to the datasets used in this exercise. Use `pd.read_csv` to read in and store `key_vilno_1.csv` and `key_vilno_2.csv` as `pid1` and `pid2` respectively.

In [143]:
data_filepath1 = "https://courses.edx.org/asset-v1:HarvardX+PH526x+2T2019+type@asset+block@key_vilno_1.csv"
data_filepath2 = "https://courses.edx.org/asset-v1:HarvardX+PH526x+2T2019+type@asset+block@key_vilno_2.csv"

# Enter code here!
pid1 = pd.read_csv(data_filepath1, header=None, names=['idx', 'ID'])
pid2 = pd.read_csv(data_filepath2, header=None, names=['idx', 'ID'])

pid1[pid1.idx == 100], pid1.iloc[100]

(       idx      ID
 101  100.0  102205,
 idx        99.0
 ID     102204.0
 Name: 100, dtype: float64)

### Exercise 7

In this exercise, we will compute the homophily of several network characteristics for Villages 1 and 2 and compare them to homophily due to chance alone. The networks for these villages have been stored as networkx graph objects `G1` and `G2`.

#### Instructions 

- Use your `homophily()` function to compute the observed homophily for sex, caste, and religion in Villages 1 and 2. Print all six values.
- Use the `chance_homophily()` to compare these values to chance homophily. Are these values higher or lower than that expected by chance?

In [152]:
import networkx as nx
A1 = np.array(pd.read_csv("https://courses.edx.org/asset-v1:HarvardX+PH526x+2T2019+type@asset+block@adj_allVillageRelationships_vilno1.csv", index_col=0))
A2 = np.array(pd.read_csv("https://courses.edx.org/asset-v1:HarvardX+PH526x+2T2019+type@asset+block@adj_allVillageRelationships_vilno2.csv", index_col=0))
G1 = nx.to_networkx_graph(A1)
G2 = nx.to_networkx_graph(A2)

pid1 = pd.read_csv(data_filepath1, dtype=int)['0'].to_dict()
pid2 = pd.read_csv(data_filepath2, dtype=int)['0'].to_dict()

# Enter your code here!
# h1 = homophily(G1, sex1, pid1)
# h1

ref = {'sex1': sex1, 'sex2': sex2, 'caste1':caste1, 'caste2':caste2, 'religion1': religion1, 'religion2': religion2, }
for k, v in ref.items():
    print('chance_homophily[{}] : {}'.format(k, chance_homophily(v)))
    if '1' in k:
        print('homophily {}'.format(homophily(G1, v, pid1)))
    else:
        print('homophily {}'.format(homophily(G2, v, pid2)))
    print('\n')

chance_homophily[sex1] : 0.5027299861680701
homophily 0.5908629441624366


chance_homophily[sex2] : 0.5005945303210464
homophily 0.5658073270013568


chance_homophily[caste1] : 0.6741488509791551
homophily 0.7959390862944162


chance_homophily[caste2] : 0.425368244800893
homophily 0.8276797829036635


chance_homophily[religion1] : 0.9804896988521925
homophily 0.9908629441624366


chance_homophily[religion2] : 1.0
homophily 1.0